server/src/main/java/com/frbenio/lockingApp/database/model/Role.java
package com.frbenio.lockingApp.database.model;

import com.frbenio.lockingApp.database.model.consts.MongoCollections;
import org.bson.types.ObjectId;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.DBRef;
import org.springframework.data.mongodb.core.mapping.Document;

import java.io.Serializable;
import java.util.List;

/**
 * Created by frben on 24.10.2016.
 */
@Document(collection = MongoCollections.ROLES)
public class Role implements Serializable {

    @Id
    private ObjectId mongoId;
    private String name;
    @DBRef(lazy = true)
    private List<Room> rooms;

    public ObjectId getMongoId() {
        return mongoId;
    }
    public void setMongoId(ObjectId mongoId) {
        this.mongoId = mongoId;
    }
    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }
    public List<Room> getRooms() {
        return rooms;
    }
    public void setRooms(List<Room> rooms) {
        this.rooms = rooms;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Role role = (Role) o;

        if (mongoId != null ? !mongoId.equals(role.mongoId) : role.mongoId != null) return false;
        return name != null ? name.equals(role.name) : role.name == null;

    }

    @Override
    public int hashCode() {
        int result = mongoId != null ? mongoId.hashCode() : 0;
        result = 31 * result + (name != null ? name.hashCode() : 0);
        return result;
    }

    @Override
    public String toString() {
        return "Role{" +
                "mongoId=" + mongoId +
                ", name='" + name + '\'' +
                ", rooms=" + rooms +
                '}';
    }
}

server/src/main/java/com/frbenio/lockingApp/database/model/Space.java
package com.frbenio.lockingApp.database.model;

import org.bson.types.ObjectId;
import org.springframework.data.annotation.Id;

/**
 * Created by frben on 25.11.2016.
 */
public abstract class Space {

    @Id
    protected ObjectId mongoId;
    protected String name;
    protected boolean root;

    public ObjectId getMongoId() {
        return mongoId;
    }

    public void setMongoId(ObjectId mongoId) {
        this.mongoId = mongoId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public boolean isRoot() {
        return root;
    }

    public void setRoot(boolean root) {
        this.root = root;
    }

    @Override
    public String toString() {
        return "Space{" +
                "mongoId=" + mongoId +
                ", name='" + name + '\'' +
                ", root='" + root + '\'' +
                '}';
    }
}

server/src/main/java/com/frbenio/lockingApp/database/model/User.java
package com.frbenio.lockingApp.database.model;

import com.frbenio.lockingApp.database.model.consts.MongoCollections;
import org.bson.types.ObjectId;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.DBRef;
import org.springframework.data.mongodb.core.mapping.Document;

import java.io.Serializable;

/**
 * Created by frben on 24.08.2016.
 */
@Document(collection = MongoCollections.USERS)
public class User implements Serializable {

    @Id
    private ObjectId mongoId;
    private String cardId;
    private String name;
    @DBRef
    private Role role;

    public User(){

    }

    public User(User user) {
        this.mongoId = user.getMongoId();
        this.cardId = user.getCardId();
        this.name = user.getName();
        this.role = user.getRole();
    }

    public Role getRole() {
        return role;
    }
    public void setRole(Role role) {
        this.role = role;
    }
    public String getCardId() {
        return cardId;
    }
    public void setCardId(String cardId) {
        this.cardId = cardId;
    }
    public ObjectId getMongoId() {
        return mongoId;
    }
    public void setMongoId(ObjectId mongoId) {
        this.mongoId = mongoId;
    }
    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        User user = (User) o;

        if (cardId != null ? !cardId.equals(user.cardId) : user.cardId != null) return false;
        if (name != null ? !name.equals(user.name) : user.name != null) return false;
        return role != null ? role.equals(user.role) : user.role == null;

    }

    @Override
    public int hashCode() {
        int result = cardId != null ? cardId.hashCode() : 0;
        result = 31 * result + (name != null ? name.hashCode() : 0);
        result = 31 * result + (role != null ? role.hashCode() : 0);
        return result;
    }

    @Override
    public String toString() {
        return "User{" +
                "mongoId=" + mongoId +
                ", cardId='" + cardId + '\'' +
                ", name='" + name + '\'' +
                '}';
    }
}

server/src/main/java/com/frbenio/lockingApp/jsf/controller/EditRoleController.java
package com.frbenio.lockingApp.jsf.controller;

import com.frbenio.lockingApp.database.model.Group;
import com.frbenio.lockingApp.database.model.Role;
import com.frbenio.lockingApp.database.model.Room;
import com.frbenio.lockingApp.database.service.RolesService;
import com.frbenio.lockingApp.database.service.SpaceService;
import org.bson.types.ObjectId;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by frben on 27.08.2016.
 */
@Component
@Scope("singleton")
public class EditRoleController {

    private final RolesService rolesService;
    private final SpaceService spaceService;

    @Autowired
    public EditRoleController(RolesService rolesService, SpaceService spaceService) {
        this.rolesService = rolesService;
        this.spaceService = spaceService;
    }

    public void save(Role role) {
        rolesService.save(role);
    }

    public List<Group> getFirstTierGroups() {
        return spaceService.getFirstTierGroups();
    }

    public List<Room> getFirstTierRooms() {
        return spaceService.getFirstTierRooms();
    }

    public List<Room> getOnlyRoomChildren(Group group) {
        List<Room> children = new ArrayList<>();
        if(group.getGroups() != null){
            for (Group childGroup : group.getGroups()) {
                children.addAll(getOnlyRoomChildren(childGroup));
            }
        }
        if(group.getRooms() != null){
            children.addAll(group.getRooms());
        }
        return children;
    }

    public Group getGroupById(ObjectId mongoId) {
        return spaceService.getGroupById(mongoId);
    }
}

server/src/main/java/com/frbenio/lockingApp/jsf/controller/ErrorController.java
package com.frbenio.lockingApp.jsf.controller;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import javax.faces.context.FacesContext;

/**
 * Created by frben on 04.09.2016.
 */
@Component
@Scope("request")
public class ErrorController {

    public String getStatusCode(){
        return String.valueOf((Integer) FacesContext.getCurrentInstance().getExternalContext().
                getRequestMap().get("javax.servlet.error.status_code"));
    }

}

server/src/main/java/com/frbenio/lockingApp/jsf/controller/RolesController.java
package com.frbenio.lockingApp.jsf.controller;

import com.frbenio.lockingApp.database.model.Role;
import com.frbenio.lockingApp.database.service.RolesService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import java.util.List;

/**
 * Created by frben on 24.10.2016.
 */
@Component
@Scope("singleton")
public class RolesController {

    private final RolesService rolesService;

    @Autowired
    public RolesController(RolesService rolesService) {
        this.rolesService = rolesService;
    }

    public List<Role> getRoles() {
        return rolesService.getRoles();
    }

    public void addRole(Role newRole) {
        rolesService.addRole(newRole);
    }

    public void deleteRole(Role role) {
        rolesService.deleteRole(role);
    }
}

server/src/main/java/com/frbenio/lockingApp/jsf/controller/SettingController.java
package com.frbenio.lockingApp.jsf.controller;

import com.frbenio.lockingApp.database.service.AdminService;
import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;

/**
 * Created by frben on 25.09.2016.
 */
@Component
@Scope("singleton")
public class SettingController {

    private AdminService adminService;

    @Autowired
    public SettingController(AdminService adminService) {
        this.adminService = adminService;
    }

    public void changeLogin(String newLogin){
        adminService.updateLogin(newLogin);
    }

    public void changePassword(String newPassword){
        adminService.updatePassword(newPassword);
    }

    public boolean validateCurrentPassword(String password){
        return adminService.validateCurrentPassword(password);
    }

    public StreamedContent getLogsFile() throws FileNotFoundException {
        File logsFile = new File("C:\\Users\\frben\\workspace\\inż\\lockingApp\\requests.log");
        InputStream stream = new FileInputStream(logsFile);
        return new DefaultStreamedContent(stream, "text/plain", "requests.log");
    }

}

server/src/main/java/com/frbenio/lockingApp/jsf/controller/SpacesController.java
package com.frbenio.lockingApp.jsf.controller;

import com.frbenio.lockingApp.database.model.Group;
import com.frbenio.lockingApp.database.model.Room;
import com.frbenio.lockingApp.database.model.Space;
import com.frbenio.lockingApp.database.service.SpaceService;
import org.bson.types.ObjectId;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import java.util.List;

/**
 * Created by frben on 09.07.2016.
 */
@Component
@Scope("singleton")
public class SpacesController {

    private final SpaceService spaceService;

    @Autowired
    public SpacesController(SpaceService spaceService) {
        this.spaceService = spaceService;
    }

    public List<Group> getFirstTierGroups() {
        return spaceService.getFirstTierGroups();
    }

    public List<Room> getFirstTierRooms() {
        return spaceService.getFirstTierRooms();
    }

    public void save(Space newSpace) {
        spaceService.save(newSpace);
    }

    public void deleteRoom(Room room) {
        spaceService.deleteSpace(room);
    }

    public void deleteGroup(Group group) {
        if(group.getGroups() != null){
            for (Group singleGroup : group.getGroups()) {
                deleteGroup(singleGroup);
                spaceService.deleteSpace(singleGroup);
            }
        }
        if(group.getRooms() != null){
            group.getRooms().forEach(spaceService::deleteSpace);
        }
        spaceService.deleteSpace(group);
    }

    public Group getGroupById(ObjectId mongoId) {
        return spaceService.getGroupById(mongoId);
    }

    public boolean idAlreadyExists(Room editingRoom) {
        Room roomById = spaceService.findRoomByLockId(editingRoom.getLockId());
        if(roomById == null){
            return false;
        }
        return !roomById.getMongoId().equals(editingRoom.getMongoId());
    }
}

server/src/main/java/com/frbenio/lockingApp/jsf/controller/UserController.java
package com.frbenio.lockingApp.jsf.controller;

import com.frbenio.lockingApp.database.model.Role;
import com.frbenio.lockingApp.database.model.User;
import com.frbenio.lockingApp.database.service.RolesService;
import com.frbenio.lockingApp.database.service.UserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import java.util.List;

/**
 * Created by frben on 26.08.2016.
 */
@Component
@Scope("singleton")
public class UserController {

    private final UserService userService;
    private final RolesService rolesService;

    @Autowired
    public UserController(UserService userService, RolesService rolesService) {
        this.userService = userService;
        this.rolesService = rolesService;
    }

    public List<User> getUsers() {
        return userService.fetchAll();
    }

    public List<Role> getAllRoles() {
        return rolesService.getRoles();
    }

    public void addUser(User user) {
        userService.save(user);
    }

    public void deleteUser(User user){
        userService.delete(user);
    }

    public boolean idAlreadyExists(String cardId) {
        return userService.findByCardId(cardId) != null;
    }

    public boolean idAlreadyExists(User editingUser) {
        User userById = userService.findByCardId(editingUser.getCardId());
        return userById != null && !userById.getMongoId().equals(editingUser.getMongoId());
    }

    public void saveUser(User user) {
        userService.save(user);
    }

}

server/src/main/webapp/views/error.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xml:lang="en" lang="en">
<h:head>
    <title>#{i18n['main.applicationName']}</title>
</h:head>
<h:body>

    <h:outputStylesheet name="css/style.css" />

    <div class="page">

        <div class="page-content">
            <p:panel id="content">
                <div id="error">
                    <h:outputText value= "#{errorController.statusCode}"/>
                </div>
            </p:panel>
        </div>

    </div>


</h:body>
</html>

server/src/main/webapp/views/header.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html
        PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui" xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets">

<h:form>

    <p:toolbar>
        <f:facet name="left">
            <ui:insert name="header-buttons">
                <p:commandButton value="#{i18n['main.doors']}" icon="fa fa-fw fa-unlock-alt small-icon"
                                 styleClass="header-button" action="spaces"/>
                <p:commandButton value="#{i18n['main.users']}" icon="fa fa-fw fa-user small-icon"
                                 styleClass="header-button" action="users"/>
                <span class="ui-separator">
                    <span class="ui-icon ui-icon-grip-dotted-vertical"/>
                </span>
                <p:commandButton value="#{i18n['main.roles']}" icon="fa fa-fw fa-key small-icon"
                                 styleClass="header-button" action="roles"/>
            </ui:insert>
        </f:facet>

        <f:facet name="right">
            <p:menuButton value="#{i18n['main.options']}" styleClass="header-button">
                <p:menuitem value="#{i18n['main.credentials']}" action="settings" styleClass="option-button"/>
                <p:menuitem value="#{i18n['main.logs']}" ajax="false" styleClass="option-button">
                    <p:fileDownload value="#{settingController.logsFile}"/>
                </p:menuitem>
            </p:menuButton>

            <p:commandButton value="#{i18n['main.logout']}" icon="fa fa-fw fa-sign-out small-icon"
                             styleClass="header-button" action="#{authController.logout}"/>
        </f:facet>

    </p:toolbar>

</h:form>


</html>

server/src/main/webapp/views/login.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html
        PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xml:lang="en" lang="en">
<h:head>
    <title>#{i18n['main.applicationName']}</title>
</h:head>
<h:body>

    <h:outputStylesheet name="css/login.css" />

    <div class="flex-container">

        <p:panel id="login-panel">
            <p:fragment rendered="#{not empty param.error}">
                <div id="error-message">#{i18n['login.bad_credentials']}</div>
            </p:fragment>
            <h:form id="loginForm" prependId="false">
                <p:panelGrid columns="1">
                    <p:inputText id="login" placeholder="#{i18n['login.login_placeholder']}"/>
                    <p:password id="password" placeholder="#{i18n['login.password_placeholder']}"/>
                </p:panelGrid>

                <p:commandButton id="login-button" action="#{authController.login}" value="#{i18n['login.login_button']}" update="@form" ajax="false" />
            </h:form>
        </p:panel>
    </div>

</h:body>
</html>

server/src/main/webapp/views/settings.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html
        PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:f="http://xmlns.jcp.org/jsf/core">
<ui:composition template="/template/master-page.xhtml">

    <ui:define name="content">
        <h:outputStylesheet name="css/settings.css"/>

        <p:messages for="settingsMessages" showDetail="true" closable="true" autoUpdate="true" />

        <h:form id="change-login-form">
            <p:panelGrid columns="1" styleClass="settings-panel">
                <p:messages for="new-login" autoUpdate="true"/>
                <p:inputText id="new-login" placeholder="Nowy login" value="#{settingModel.newLogin}" styleClass="settings-input">
                    <f:validateLength minimum="5"/>
                </p:inputText>
                <p:messages for="change-login-password" autoUpdate="true"/>
                <p:password id="change-login-password" placeholder="Hasło" value="#{settingModel.password}" styleClass="settings-input"/>
                <p:commandButton action="#{settingModel.changeLogin()}" value="#{i18n['settings.change_login']}" update="change-login-form" styleClass="settings-button"/>
            </p:panelGrid>
        </h:form>

        <hr/>

        <h:form id="change-password-form">
            <p:panelGrid columns="1" styleClass="settings-panel">
                <p:messages for="old-password" autoUpdate="true"/>
                <p:password id="old-password" placeholder="Stare hasło" value="#{settingModel.password}" styleClass="settings-input"/>
                <p:messages for="new-password" autoUpdate="true"/>
                <p:password id="new-password" placeholder="Nowe hasło" value="#{settingModel.newPassword}" styleClass="settings-input">
                    <f:validateLength minimum="5"/>
                </p:password>
                <p:messages for="new-password-repeat" autoUpdate="true"/>
                <p:password id="new-password-repeat" placeholder="Powtórz hasło" value="#{settingModel.newPasswordRepeated}" styleClass="settings-input"/>
                <p:commandButton action="#{settingModel.changePassword()}" value="#{i18n['settings.change_password']}" update="change-password-form" styleClass="settings-button"/>
            </p:panelGrid>
        </h:form>

    </ui:define>

</ui:composition>
</html>

server/src/main/webapp/views/users.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html
        PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:f="http://xmlns.jcp.org/jsf/core">
<ui:composition template="/template/master-page.xhtml">

    <ui:define name="header-buttons">
        <p:commandButton value="#{i18n['main.doors']}" icon="fa fa-fw fa-unlock-alt small-icon"
                         styleClass="header-button" action="spaces"/>
        <p:commandButton value="#{i18n['main.users']}" icon="fa fa-fw fa-user small-icon"
                         styleClass="header-button" action="users" disabled="true"/>
        <span class="ui-separator">
                    <span class="ui-icon ui-icon-grip-dotted-vertical"/>
                </span>
        <p:commandButton value="#{i18n['main.roles']}" icon="fa fa-fw fa-key small-icon"
                         styleClass="header-button" action="roles"/>
    </ui:define>

    <ui:define name="content">
        <p:messages for="userMessages" showDetail="true" autoUpdate="true" closable="true"/>

        <h:form id="userListForm">
            <p:dataTable id="userList" value="#{userModel.users}" var="user"
                         emptyMessage="#{i18n['main.table_empty_message']}">
                <p:column headerText="#{i18n['user.card_id']}" filterBy="#{user.cardId}" style="width: 25%;">
                    <h:outputText value="#{user.cardId}" styleClass="table-column"/>
                </p:column>
                <p:column headerText="#{i18n['user.user_name']}" filterBy="#{user.name}">
                    <h:outputText value="#{user.name}" styleClass="table-column credentials-column"/>
                </p:column>
                <p:column headerText="#{i18n['user.role']}" filterBy="#{user.role.name}"
                          style="width: 20%; text-align: center">
                    <h:outputText value="#{user.role.name}" styleClass="table-column credentials-column"/>
                </p:column>
                <p:column styleClass="double-icon-column">
                    <p:commandLink actionListener="#{userModel.editUser(user)}"
                                   update="editPanelForm:editPanel">
                        <p:graphicImage library="images" name="edit-icon.png" styleClass="table-icon"
                                        onmouseover="document.getElementById(this.id).src='/javax.faces.resource/edit-icon-hover.png.xhtml?ln=images'"
                                        onmouseout="document.getElementById(this.id).src='/javax.faces.resource/edit-icon.png.xhtml?ln=images'"/>
                    </p:commandLink>
                    <p:commandLink actionListener="#{userModel.deleteUser(user)}" update="userList">
                        <p:graphicImage library="images" name="remove-icon.png" styleClass="table-icon"
                                        onmouseover="document.getElementById(this.id).src='/javax.faces.resource/remove-icon-hover.png.xhtml?ln=images'"
                                        onmouseout="document.getElementById(this.id).src='/javax.faces.resource/remove-icon.png.xhtml?ln=images'"/>
                        <p:confirm header="Potwierdzenie" message="#{i18n['user.remove_message']} #{user.name}? "
                                   icon="ui-icon-blank"/>
                    </p:commandLink>
                </p:column>
            </p:dataTable>

            <div class="add-panel">
                <p:commandLink onclick="PF('addDialog').show();" update="addPanelForm:addPanel">
                    <p:graphicImage styleClass="add-button" library="images" name="add-icon.png"
                                    onmouseover="document.getElementById(this.id).src='/javax.faces.resource/add-icon-hover.png.xhtml?ln=images'"
                                    onmouseout="document.getElementById(this.id).src='/javax.faces.resource/add-icon.png.xhtml?ln=images'"/>
                </p:commandLink>
            </div>
        </h:form>


        <p:dialog header="#{i18n['user.add_dialog_header']}" widgetVar="addDialog" resizable="false" draggable="false"
                  modal="true" closable="false">
            <h:form id="addPanelForm">
                <div class="edit-panel">
                    <p:panelGrid id="addPanel">
                        <p:row>
                            <p:column colspan="2"><p:messages for="newUserName" showIcon="false"/></p:column>
                        </p:row>
                        <p:row>
                            <p:column><p:outputLabel for="newUserName" value="#{i18n['user.user_name']}:"/></p:column>
                            <p:column><p:inputText id="newUserName" value="#{userModel.newUser.name}" required="true">
                                <f:validateLength maximum="36"/>
                            </p:inputText></p:column>
                        </p:row>
                        <p:row>
                            <p:column colspan="2"><p:messages for="newUserCardId" showIcon="false"/></p:column>
                        </p:row>
                        <p:row>
                            <p:column><p:outputLabel for="newUserCardId" value="#{i18n['user.card_id']}:"/></p:column>
                            <p:column><p:inputText id="newUserCardId" value="#{userModel.newUser.cardId}"
                                                   required="true">
                                <f:validateLength maximum="18"/>
                            </p:inputText></p:column>
                        </p:row>
                        <p:row>
                            <p:column colspan="2"><p:messages for="newUserRole" showIcon="false"/></p:column>
                        </p:row>
                        <p:row>
                            <p:column colspan="2">
                                <p:selectOneMenu id="newUserRole" value="#{userModel.newUser.role}"
                                                 style="width: 88%" converter="#{roleConverter}">
                                    <f:selectItem itemLabel="Uprawnienia" itemValue="#{null}" noSelectionOption="true"/>
                                    <f:selectItems value="#{userModel.allRoles}" var="role" itemLabel="#{role.name}"
                                                   itemValue="#{role}"/>
                                </p:selectOneMenu>
                            </p:column>
                        </p:row>
                    </p:panelGrid>

                    <div class="dialog-buttons-panel">
                        <p:commandButton value="#{i18n['main.cancel']}"
                                         icon="fa fa-fw fa-close small-icon"
                                         process="@this"
                                         oncomplete="PF('addDialog').hide();" styleClass="dialog-cancel-button">
                            <p:resetInput target="addPanelForm"/>
                        </p:commandButton>
                        <p:commandButton value="#{i18n['main.add']}" actionListener="#{userModel.addUser()}"
                                         update="userListForm:userList addPanel"
                                         icon="fa fa-fw fa-plus small-icon" styleClass="dialog-add-button"/>
                    </div>
                </div>
            </h:form>
        </p:dialog>

        <p:dialog header="#{i18n['edit_user.edit_dialog_header']}" widgetVar="editDialog" resizable="false"
                  draggable="false" modal="true" closable="false">
            <h:form id="editPanelForm">
                <div class="edit-panel">
                    <p:panelGrid id="editPanel">
                        <p:row>
                            <p:column colspan="2"><p:messages for="editUserName" display="text"/></p:column>
                        </p:row>
                        <p:row>
                            <p:column><p:outputLabel for="editUserName" value="#{i18n['user.user_name']}:"/></p:column>
                            <p:column><p:inputText id="editUserName" value="#{userModel.copyOfEditingUser.name}"
                                                   required="true">
                                <f:validateLength maximum="36"/>
                            </p:inputText></p:column>
                        </p:row>
                        <p:row>
                            <p:column colspan="2"><p:messages for="editUserCardId" display="text"/></p:column>
                        </p:row>
                        <p:row>
                            <p:column><p:outputLabel for="editUserCardId" value="#{i18n['user.card_id']}:"/></p:column>
                            <p:column><p:inputText id="editUserCardId" value="#{userModel.copyOfEditingUser.cardId}"
                                                   required="true">
                                <f:validateLength maximum="18"/>
                            </p:inputText></p:column>
                        </p:row>
                        <p:row>
                            <p:column colspan="2"><p:messages for="editUserRole" showIcon="false"/></p:column>
                        </p:row>
                        <p:row>
                            <p:column colspan="2">
                                <p:selectOneMenu id="editUserRole" value="#{userModel.copyOfEditingUser.role}"
                                                 style="width: 88%" converter="#{roleConverter}">
                                    <f:selectItem itemLabel="Uprawnienia" itemValue="#{null}" noSelectionOption="true"/>
                                    <f:selectItems value="#{userModel.allRoles}" var="role" itemLabel="#{role.name}"
                                                   itemValue="#{role}"/>
                                </p:selectOneMenu>
                            </p:column>
                        </p:row>
                    </p:panelGrid>

                    <div class="dialog-buttons-panel">
                        <p:commandButton value="#{i18n['main.cancel']}"
                                         icon="fa fa-fw fa-close small-icon"
                                         process="@this"
                                         oncomplete="PF('editDialog').hide();" styleClass="dialog-cancel-button">
                            <p:resetInput target="editPanelForm"/>
                        </p:commandButton>
                        <p:commandButton value="#{i18n['main.save']}" actionListener="#{userModel.saveUser()}"
                                         update="userListForm:userList editPanel"
                                         icon="fa fa-fw fa-check small-icon"/>
                    </div>
                </div>
            </h:form>
        </p:dialog>

    </ui:define>

</ui:composition>
</html>